#!/usr/bin/env python3
"""Copy a single reference document into a plugin, with provenance.

Used for documents small enough that one sub-agent can read the whole thing,
so splitting them would only add dispatch overhead. For anything larger, see
chunk.py.

Usage:
    vendor.py --source-url URL --title TITLE --out FILE [--html] INPUT
"""

import argparse
import os
import re
from datetime import date

import chunk as chunklib
import htmlmd

GENERATED_BY = "scripts/sync-references.sh"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("--out", required=True, help="output file path")
    ap.add_argument("--source-url", required=True)
    ap.add_argument("--title", required=True)
    ap.add_argument("--html", action="store_true", help="input is HTML")
    ap.add_argument("--code-lang", default="", help="language tag for code fences")
    args = ap.parse_args()

    with open(args.input, encoding="utf-8") as f:
        text = f.read()
    if args.html:
        text = htmlmd.convert(text, code_lang=args.code_lang)
    text = re.sub(r"^\{%\s*(end)?raw\s*%\}\s*$", "", text, flags=re.M)

    sha = chunklib.upstream_commit(args.input)
    header = (
        f"<!-- Generated by {GENERATED_BY}. Do not edit. -->\n"
        f"# {args.title}\n\n"
        f"Source: {args.source_url} (upstream {sha}, synced {date.today().isoformat()})\n\n"
        "---\n\n"
    )
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(header + text.strip() + "\n")

    print(f"{args.title}: 1 file -> {args.out}")


if __name__ == "__main__":
    main()
