#!/usr/bin/env bash
# Regenerate the reference documents each review plugin ships.
#
# Upstream style guides live in third_party/ as git submodules. Plugins can't
# read them at review time: installing a plugin copies its directory into
# ~/.claude/plugins/cache, and a submodule's contents don't come along. So the
# guides are converted, chunked, and committed into each plugin instead.
#
# Regenerates from whatever the submodules are currently checked out at. To move
# them first, and for how to check them out at all, see DEV.md.
#
# Review the diff before committing: upstream rewrites shift chunk boundaries,
# and the skills name chunk files.

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

lib="$repo_root/scripts/lib"
tp="$repo_root/third_party"
chunk() { python3 "$lib/chunk.py" "$@"; }
vendor() { python3 "$lib/vendor.py" "$@"; }

for m in styleguide abseil-docs go go-website; do
  if [[ ! -e "$tp/$m/.git" ]]; then
    echo "error: $tp/$m is not checked out. See DEV.md." >&2
    exit 1
  fi
done

STYLE=https://google.github.io/styleguide
ABSEIL=https://abseil.io/docs

# ---------------------------------------------------------------- Go plugin

go_refs="$repo_root/plugins/google-go-review/references"
echo "==> google-go-review"

chunk "$tp/go-website/_content/doc/effective_go.html" \
  --out "$go_refs/effective-go" --html --code-lang go \
  --source-url https://go.dev/doc/effective_go --title "Effective Go"

vendor "$tp/styleguide/go/index.md" \
  --out "$go_refs/style-overview.md" \
  --source-url "$STYLE/go/index" --title "Go Style at Google: Overview"

vendor "$tp/styleguide/go/guide.md" \
  --out "$go_refs/style-guide.md" \
  --source-url "$STYLE/go/guide" --title "Go Style Guide (core, canonical)"

chunk "$tp/styleguide/go/best-practices.md" \
  --out "$go_refs/style-best-practices" \
  --source-url "$STYLE/go/best-practices" --title "Go Style Best Practices"

chunk "$tp/styleguide/go/decisions.md" \
  --out "$go_refs/style-decisions" \
  --source-url "$STYLE/go/decisions" --title "Go Style Decisions"

chunk "$tp/go/doc/go_spec.html" \
  --out "$go_refs/go-spec" --html --code-lang go --level 2 \
  --source-url https://go.dev/ref/spec --title "The Go Programming Language Specification"

chunk "$tp/go-website/_content/ref/mod.md" \
  --out "$go_refs/go-modules" --level 2 \
  --source-url https://go.dev/ref/mod --title "Go Modules Reference"

# --------------------------------------------------------------- C++ plugin

cpp_refs="$repo_root/plugins/google-cpp-review/references"
echo "==> google-cpp-review"

chunk "$tp/styleguide/cppguide.html" \
  --out "$cpp_refs/cpp-style-guide" --html --code-lang c++ \
  --source-url "$STYLE/cppguide.html" --title "Google C++ Style Guide"

vendor "$tp/abseil-docs/docs/cpp/atomic_danger.md" \
  --out "$cpp_refs/abseil/atomic-danger.md" \
  --source-url "$ABSEIL/cpp/atomic_danger" --title "Abseil: Danger of Atomics"

# ------------------------------------------------------------ Python plugin

py_refs="$repo_root/plugins/google-python-review/references"
echo "==> google-python-review"

chunk "$tp/styleguide/pyguide.md" \
  --out "$py_refs/python-style-guide" \
  --source-url "$STYLE/pyguide.html" --title "Google Python Style Guide"

# ------------------------------------------------------- Abseil guide sets
#
# Each guide is small enough to hand to a single sub-agent whole, so these are
# copied rather than chunked. The generated index is what the skills dispatch
# from, and it doubles as the list of guides that exist upstream.

vendor_abseil_guides() {
  local lang=$1 out=$2 src="$tp/abseil-docs/docs/$1/guides"
  local index="$out/index.md" name title

  mkdir -p "$out"
  find "$out" -maxdepth 1 -name '*.md' -delete

  {
    echo "<!-- Generated by scripts/sync-references.sh. Do not edit. -->"
    echo "# Abseil $lang guides — index"
    echo
    echo "Source: $ABSEIL/$lang/guides/"
    echo
    echo "Dispatch one sub-agent per guide the code under review actually uses."
    echo
    echo "| Guide | Title |"
    echo "|---|---|"
  } >"$index"

  for doc in "$src"/*.md; do
    name=$(basename "$doc" .md)
    [[ "$name" == "index" ]] && continue
    title=$(sed -n 's/^title: *//p' "$doc" | head -1 | tr -d '"')
    title=${title:-$name}
    vendor "$doc" --out "$out/$name.md" \
      --source-url "$ABSEIL/$lang/guides/$name" --title "Abseil: $title" >/dev/null
    echo "| \`$name.md\` | $title |" >>"$index"
  done
  echo "Abseil $lang guides: $(($(wc -l <"$index") - 9)) guide(s) -> $out"
}

vendor_abseil_guides cpp "$cpp_refs/abseil/guides"
vendor_abseil_guides python "$py_refs/abseil/guides"

# ------------------------------------------------------------------ NOTICEs

# CC-BY requires naming the work, linking the license, and stating that the work
# was modified. Splitting a guide into chunks and converting it from HTML is a
# modification, so each entry says so explicitly rather than relying on one
# blanket sentence.
write_notice() {
  local out=$1
  shift
  {
    echo "<!-- Generated by scripts/sync-references.sh. Do not edit. -->"
    echo "# Third-party documentation notice"
    echo
    echo "Everything under \`references/\` is a modified copy of the documents"
    echo "listed below, redistributed under the licenses named. **Modifications:**"
    echo "converted to Markdown where the original is HTML, split into numbered"
    echo "section files, and given a generated header and index. No wording was"
    echo "changed. The upstream URL is always the canonical text."
    echo
    echo "None of the upstream authors endorse this project or its plugins."
    echo
    for entry in "$@"; do
      IFS='|' read -r name attribution url license license_url commit <<<"$entry"
      echo "## $name"
      echo
      echo "- Attribution: $attribution"
      echo "- Upstream: $url"
      echo "- Vendored at commit: \`$commit\`"
      echo "- License: [$license]($license_url)"
      echo "- Modified: yes, as described above"
      echo
    done
  } >"$out"
}

sha() { git -C "$tp/$1" rev-parse --short HEAD; }

# Apache-2.0 requires shipping a copy of the license with the redistributed
# work, and BSD requires reproducing the copyright notice and disclaimer. Copy
# the upstream license files verbatim rather than paraphrasing them.
copy_licenses() {
  local out=$1/licenses
  shift
  mkdir -p "$out"
  rm -f "$out"/*.txt
  for m in "$@"; do
    cp "$tp/$m/LICENSE" "$out/$m.txt"
  done
}

copy_licenses "$go_refs" styleguide go go-website
copy_licenses "$cpp_refs" styleguide abseil-docs
copy_licenses "$py_refs" styleguide abseil-docs

sg=$(sha styleguide)
ab=$(sha abseil-docs)
gw=$(sha go-website)
gg=$(sha go)

CCBY3=https://creativecommons.org/licenses/by/3.0/
CCBY4=https://creativecommons.org/licenses/by/4.0/
APACHE2=https://www.apache.org/licenses/LICENSE-2.0
GOOG=Google
GOAUTH="The Go Authors"

# go.dev content, which includes Effective Go, the spec, and the modules
# reference, is CC-BY-4.0; the BSD license in those repositories covers code.
# See https://go.dev/copyright.
write_notice "$go_refs/NOTICE.md" \
  "Google Go Style Guide|$GOOG|https://github.com/google/styleguide|CC-BY-3.0|$CCBY3|$sg" \
  "Effective Go and the Go Modules Reference|$GOAUTH|https://github.com/golang/website|CC-BY-4.0 (prose); embedded code samples BSD-3-Clause|$CCBY4|$gw" \
  "The Go Programming Language Specification|$GOAUTH|https://github.com/golang/go|CC-BY-4.0 (prose); embedded code samples BSD-3-Clause|$CCBY4|$gg"

write_notice "$cpp_refs/NOTICE.md" \
  "Google C++ Style Guide|$GOOG|https://github.com/google/styleguide|CC-BY-3.0|$CCBY3|$sg" \
  "Abseil C++ documentation|$GOOG|https://github.com/abseil/abseil.github.io|Apache-2.0|$APACHE2|$ab"

write_notice "$py_refs/NOTICE.md" \
  "Google Python Style Guide|$GOOG|https://github.com/google/styleguide|CC-BY-3.0|$CCBY3|$sg" \
  "Abseil Python documentation|$GOOG|https://github.com/abseil/abseil.github.io|Apache-2.0|$APACHE2|$ab"

echo "==> Done. Review 'git diff --stat plugins/*/references' before committing."
